name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: false
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  test-library:
    name: Run Library Tests
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - name: Run Compiler Tests
        run: ./gradlew library:compiler:allTests
      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          include_passed: true
          fail_on_failure: true
          annotate_notice: true
          follow_symlink: true